export const admin_lookup = `select count(*) as count from admins where email = ? or phone = ?`;
export const create_admin = `insert into admins (first_name, last_name, email, phone, password, secret_token) values (?, ?, ?, ?, ?, ?)`;
export const get_secret = `select secret_token from admins where id = ?`;
export const find_user = `select id, first_name, last_name, email, phone, email_verified, phone_verified, password from admins where email = ?`;
export const find_trainer = `select count(*) as count from trainers where email = ?`;
export const create_trainer = `insert into trainers (first_name,last_name,email) values (?,?,?)`;
export const fetch_all_trainers = `select t.*, tc.id as category_id, tc.name as category_name from trainers t left join trainer_in_categories tic on t.id = tic.trainer_id left join trainer_categories tc on tic.trainer_category_id = tc.id`;
export const fetch_trainers = `select t.*, tc.id as category_id, tc.name as category_name from trainers t left join trainer_in_categories tic on t.id = tic.trainer_id left join trainer_categories tc on tic.trainer_category_id = tc.id where t.status = 1`;
export const find_user_by_id = `select * from trainers where id in (?)`;
export const update_invite_status = `update trainers set invite_status = 1 where email = ? and invite_status = 0`;
export const find_admin = `select first_name, last_name, email, phone, email_verified, phone_verified from admins where id = ?`;
export const update_email_status = `update admins set email_verified = '1' where id = ? and email = ? and secret_token = ? and email_verified = '0'`;
export const create_category = `insert into ?? (name,description) values (?,?)`;
export const get_trainer_categories = `select tc.*, count(tic.id) as count from trainer_categories tc left join trainer_in_categories tic on tc.id = tic.trainer_category_id GROUP BY tc.id;`;
export const get_student_categories = `select sc.*, count(sic.id) as count from student_categories sc left join student_in_categories sic on sc.id = sic.student_category_id GROUP BY sc.id;`;
export const get_class_categories = `select cc.*, count(cic.id) as count from class_categories cc left join class_in_categories cic on cc.id = cic.class_category_id GROUP BY cc.id;`;
export const add_to_trainer_category = `insert into trainer_in_categories (trainer_id, trainer_category_id) values ?`;
export const add_to_student_category = `insert into student_in_categories (student_id, student_category_id) values ?`;
export const add_to_class_category = `insert into class_in_categories (class_id, class_category_id) values ?`;
export const find_one_trainer = `select t.*, tc.id as category_id, tc.name as category_name from trainers t left join trainer_in_categories tic on t.id = tic.trainer_id left join trainer_categories tc on tic.trainer_category_id = tc.id where t.id = ?`;
export const create_class = `insert into classes set ?`;
export const fetch_classes = `select * from classes`;
export const udpate_class = `update classes set ? where id = ?`;
export const delete_class = `delete from classes where id = ?`;
